# Generated by Django 4.1.1 on 2022-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_fields',
            field=models.CharField(default='def', max_length=10000),
            preserve_default=False,
        ),
    ]
