# Generated by Django 4.1.1 on 2022-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_api', '0002_form_form_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=100)),
                ('campaign_field_name', models.CharField(max_length=100)),
            ],
        ),
    ]
