# Generated by Django 4.1.1 on 2022-09-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_api', '0005_field_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='campaign_field_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='condition_field_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_api.field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='condition_field_success',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_options',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
