# Generated by Django 4.1.1 on 2022-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_api', '0006_alter_field_campaign_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='required',
            field=models.BooleanField(),
        ),
    ]
