# Generated by Django 4.1.1 on 2022-10-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_api', '0008_field_qualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_qualifier_data',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
